[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "btc_graph"
version = "0.0.1"
description = "Bitcoin blockchain graph modelling"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Ayoub Dhibi", email = "ayoub.dhibi@ens-lyon.fr" },
]
requires-python = ">=3.8"
keywords = ["bitcoin", "blockchain", "graph", "graphframe"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Documentation = "https://readthedocs.org"
Repository = "https://github.com/ayoub-dhibi-ENSL/BTC_project"
Changelog = "https://github.com/ayoub-dhibi-ENSL/BTC_project/blob/main/CHANGELOG.md"

[project.scripts]
btc-graph = "btc_graph.main:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["btc_graph*"]